{
    "config": {
        "error": {
            "cannot_connect": "Yhteyden muodostaminen ep\u00e4onnistui",
            "invalid_auth": "Virheellinen todennus",
            "unknown": "Odottamaton virhe"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Salasana",
                    "username": "K\u00e4ytt\u00e4j\u00e4tunnus"
                }
            },
            "user": {
                "data": {
                    "host": "Palvelin"
                },
                "data_description": {
                    "host": "IoTaWatt -laitteen is\u00e4nt\u00e4nimi tai IP-osoite."
                }
            }
        }
    }
}