{
    "config": {
        "abort": {
            "already_configured": "Seade on juba h\u00e4\u00e4lestatud",
            "reauth_successful": "Taastuvastamine \u00f5nnestus",
            "reconfigure_successful": "\u00dcmberseadistamine \u00f5nnestus"
        },
        "error": {
            "cannot_connect": "\u00dchendamine nurjus",
            "invalid_auth": "Tuvastamine nurjus",
            "unknown": "Ootamatu t\u00f5rge"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Salas\u00f5na",
                    "username": "Kasutajanimi"
                },
                "title": "{name} autentimine aegus"
            },
            "reconfigure_confirm": {
                "data": {
                    "host": "Host",
                    "password": "Salas\u00f5na",
                    "port": "Port",
                    "ssl": "Kasutab SSL sertifikaati",
                    "username": "Kasutajanimi",
                    "verify_ssl": "Kontrolli SSL sertifikaati"
                },
                "data_description": {
                    "host": "pyLoadi eksemplari k\u00e4itava seadme hostinimi v\u00f5i IP-aadress.",
                    "port": "pyLoad kasutab vaikimisi porti 8000."
                }
            },
            "user": {
                "data": {
                    "host": "Host",
                    "name": "Nimi",
                    "password": "Salas\u00f5na",
                    "port": "Port",
                    "ssl": "Kasutab SSL sertifikaati",
                    "username": "Kasutajanimi",
                    "verify_ssl": "Kontrolli SSL sertifikaati"
                },
                "data_description": {
                    "host": "pyLoadi eksemplari k\u00e4itava seadme hostinimi v\u00f5i IP-aadress.",
                    "name": "Nimi, mida kasutada pyLoadi eksemplari jaoks Home Assistantis",
                    "port": "pyLoad kasutab vaikimisi porti 8000."
                }
            }
        }
    },
    "entity": {
        "button": {
            "abort_downloads": {
                "name": "Katkesta k\u00f5ik t\u00f6\u00f6tavad allalaadimised"
            },
            "delete_finished": {
                "name": "Kustuta valmis failid / paketid"
            },
            "restart": {
                "name": "Taask\u00e4ivita pyloadi tuum"
            },
            "restart_failed": {
                "name": "Taask\u00e4ivita k\u00f5ik nurjunud failid"
            }
        },
        "sensor": {
            "active": {
                "name": "Aktiivsed allalaadimised"
            },
            "free_space": {
                "name": "Vaba salvestusruum"
            },
            "queue": {
                "name": "Allalaadimisi j\u00e4rjekorras"
            },
            "speed": {
                "name": "Kiirus"
            },
            "total": {
                "name": "Allalaadimised kokku"
            }
        },
        "switch": {
            "download": {
                "name": "J\u00e4rjekorra peatamine/j\u00e4tkamine"
            },
            "reconnect": {
                "name": "Automaatne taas\u00fchendamine"
            }
        }
    },
    "exceptions": {
        "service_call_auth_exception": {
            "message": "Tuvastusvea t\u00f5ttu ei saa pyLoadile k\u00e4sku saata, proovi hiljem uuesti"
        },
        "service_call_exception": {
            "message": "\u00dchenduse t\u00f5rke t\u00f5ttu ei saa pyLoadile k\u00e4sku saata, proovi hiljem uuesti"
        },
        "setup_authentication_exception": {
            "message": "Autentimine eba\u00f5nnestus {username}, kontrolli oma sisselogimise andmeid."
        },
        "setup_parse_exception": {
            "message": "PyLoad API andmeid ei ole v\u00f5imalik s\u00f5eluda, proovi hiljem uuesti"
        },
        "setup_request_exception": {
            "message": "\u00dchendust ei saa luua ja pyLoad API-st andmeid tuua, proovi hiljem uuesti"
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "PyLoadi konfigureerimine YAML-i abil eemaldatakse, kuid YAML-i konfiguratsiooni importimisel ilmnes \u00fchenduse viga. \n\n Veendu, et on olemas stabiilne Interneti-\u00fchendus ja taask\u00e4ivita Home Assistant, et uuesti proovida v\u00f5i eemalda pyLoad YAML-i konfiguratsioon failist configuration.yaml ja j\u00e4tka k\u00e4sitsi [integratsiooni seadistamisega]( {url} ).",
            "title": "PyLoad YAML-i konfiguratsiooni importimine nurjus"
        },
        "deprecated_yaml_import_issue_invalid_auth": {
            "description": "PyLoadi konfigureerimine YAML-i abil eemaldatakse kuid YAML-i konfiguratsiooni importimisel ilmnes autentimisviga. \n\n Paranda YAML-i konfiguratsioon ja taask\u00e4ivitagHome Assistant, et uuesti proovida v\u00f5i eemalda YAML-i pyLoad-konfiguratsioon failist configuration.yaml ja j\u00e4tka k\u00e4sitsi [integratsiooni seadistamisega] ( {url} ).",
            "title": "PyLoad YAML-i konfiguratsiooni importimine nurjus"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "PyLoadi konfigureerimine YAML-i abil eemaldatakse kuid YAML-i konfiguratsiooni importimisel ilmnes tundmatu viga. \n\n Veendu, et YAML-i konfiguratsioon on \u00f5ige ja taask\u00e4ivita Home Assistant, et uuesti proovida v\u00f5i eemalda YAML-i pyLoad konfiguratsioon failist configuration.yaml ja j\u00e4tka k\u00e4sitsi [integratsiooni seadistamisega]( {url} ).",
            "title": "PyLoad YAML-i konfiguratsiooni importimine nurjus"
        }
    }
}