{
    "config": {
        "abort": {
            "already_configured": "A fi\u00f3k m\u00e1r konfigur\u00e1lva van",
            "reauth_failed_existing": "Nem siker\u00fclt friss\u00edteni a konfigur\u00e1ci\u00f3s bejegyz\u00e9st. K\u00e9rem, t\u00e1vol\u00edtsa el az integr\u00e1ci\u00f3t \u00e9s \u00e1ll\u00edtsa be \u00fajra.",
            "reauth_successful": "Az \u00fajrahiteles\u00edt\u00e9s sikeres volt.",
            "unknown": "V\u00e1ratlan hiba"
        },
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_api_key": "\u00c9rv\u00e9nytelen API kulcs",
            "not_main_key": "Nem megfelel\u0151 API-kulcst\u00edpus, haszn\u00e1lja a \"main\" API-kulcsot",
            "reauth_failed_matching_account": "A megadott API -kulcs nem egyezik a megl\u00e9v\u0151 konfigur\u00e1ci\u00f3 fi\u00f3kazonos\u00edt\u00f3j\u00e1val.",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "api_key": "API kulcs"
                },
                "description": "Meg kell adnia egy \u00faj \u201ef\u0151\u201d API-kulcsot az UptimeRobott\u00f3l",
                "title": "A(z) {name} hiteles\u00edt\u00e9se lej\u00e1rt"
            },
            "user": {
                "data": {
                    "api_key": "API kulcs"
                },
                "description": "Meg kell adnia a \u201ef\u0151\u201d API-kulcsot az UptimeRobott\u00f3l"
            }
        }
    },
    "entity": {
        "sensor": {
            "monitor_status": {
                "state": {
                    "down": "Nem el\u00e9rhet\u0151",
                    "not_checked_yet": "M\u00e9g nincs ellen\u0151rizve",
                    "pause": "Sz\u00fcneteltet\u00e9s",
                    "seems_down": "Nem el\u00e9rhet\u0151nek t\u0171nik",
                    "up": "El\u00e9rhet\u0151"
                }
            }
        }
    }
}