{
    "config": {
        "abort": {
            "already_configured": "El dispositivo ya est\u00e1 configurado",
            "heater_not_available": "Calefactor no disponible. Intenta reiniciar el calentador presionando + y OK durante unos segundos.",
            "heater_not_found": "No se encontr\u00f3 el calentador. Intenta acercar el calentador al ordenador con Home Assistant.",
            "invalid_auth": "Autenticaci\u00f3n no v\u00e1lida"
        },
        "error": {
            "cannot_connect": "No se pudo conectar"
        },
        "step": {
            "cloud": {
                "data": {
                    "account_id": "ID de la cuenta",
                    "password": "Contrase\u00f1a"
                }
            },
            "local": {
                "data": {
                    "wifi_pswd": "Contrase\u00f1a Wi-Fi",
                    "wifi_ssid": "SSID Wi-Fi"
                },
                "description": "Reinicia el calentador pulsando + y OK hasta que la pantalla muestre 'Restablecer'. Luego mant\u00e9n pulsado el bot\u00f3n OK en el calentador hasta que el led azul comience a parpadear antes de pulsar Enviar. La configuraci\u00f3n del calentador puede tardar algunos minutos."
            },
            "user": {
                "data": {
                    "connection_type": "Selecciona el tipo de conexi\u00f3n"
                },
                "description": "Selecciona el tipo de conexi\u00f3n. Local requiere calefactores con bluetooth"
            }
        }
    }
}