{
    "config": {
        "error": {
            "cannot_connect": "Nie mo\u017cna nawi\u0105za\u0107 po\u0142\u0105czenia",
            "invalid_auth": "W\u0142\u0105cz uwierzytelnianie w Preferencjach m\u00fctesync > Uwierzytelnianie",
            "unknown": "Nieoczekiwany b\u0142\u0105d"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Host"
                }
            }
        }
    }
}