{
    "config": {
        "abort": {
            "already_configured": "A szolg\u00e1ltat\u00e1s m\u00e1r konfigur\u00e1lva van",
            "reauth_successful": "Az \u00fajrahiteles\u00edt\u00e9s sikeres volt."
        },
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_api_key": "\u00c9rv\u00e9nytelen API kulcs",
            "invalid_user_key": "\u00c9rv\u00e9nytelen felhaszn\u00e1l\u00f3i kulcs"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "api_key": "API kulcs"
                },
                "title": "A(z) {name} hiteles\u00edt\u00e9se lej\u00e1rt"
            },
            "user": {
                "data": {
                    "api_key": "API kulcs",
                    "name": "Elnevez\u00e9s",
                    "user_key": "Felhaszn\u00e1l\u00f3i kulcs"
                }
            }
        }
    },
    "issues": {
        "removed_yaml": {
            "description": "A Pushover YAML haszn\u00e1lat\u00e1val t\u00f6rt\u00e9n\u0151 konfigur\u00e1l\u00e1sa elt\u00e1vol\u00edt\u00e1sra ker\u00fclt.\n\nA megl\u00e9v\u0151 YAML konfigur\u00e1ci\u00f3j\u00e1t a Home Assistant nem haszn\u00e1lja.\n\nA hiba kijav\u00edt\u00e1s\u00e1hoz t\u00e1vol\u00edtsa el a Pushover YAML konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l \u00e9s ind\u00edtsa \u00fajra a Home Assistantot.",
            "title": "A Pushover YAML konfigur\u00e1ci\u00f3 elt\u00e1vol\u00edt\u00e1sra ker\u00fclt"
        }
    }
}